apiVersion: v1
kind: PersistentVolume
metadata:
  name: trillian-tiny-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-trillian
  local:
    path: /mnt/k8s-data/tiny-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - trillian
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trillian-small-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-trillian
  local:
    path: /mnt/k8s-data/small-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - trillian
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trillian-medium-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-trillian
  local:
    path: /mnt/k8s-data/medium-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - trillian
