apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disasterarea-tiny-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-disasterarea
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disasterarea-small-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-disasterarea
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disasterarea-medium-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-disasterarea
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disasterarea-large-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-disasterarea
  resources:
    requests:
      storage: 50Gi