apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-storage-setup-arthur
spec:
  selector:
    matchLabels:
      app: local-storage-setup
  template:
    metadata:
      labels:
        app: local-storage-setup
    spec:
      nodeSelector:
        kubernetes.io/hostname: arthur
      containers:
      - name: storage-setup
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p /mnt/k8s-data/tiny-1 /mnt/k8s-data/tiny-2 /mnt/k8s-data/small-1 /mnt/k8s-data/medium-1 /mnt/k8s-data/large-1 && chmod 777 /mnt/k8s-data/tiny-1 /mnt/k8s-data/tiny-2 /mnt/k8s-data/small-1 /mnt/k8s-data/medium-1 /mnt/k8s-data/large-1 && sleep infinity"]
        volumeMounts:
        - name: local-storage
          mountPath: /mnt/k8s-data
      volumes:
      - name: local-storage
        hostPath:
          path: /mnt/k8s-data
          type: DirectoryOrCreate
