apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-distributed-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-distributed
  resources:
    requests:
      storage: 10Gi