apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-storage-setup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: local-storage-setup
  template:
    metadata:
      labels:
        app: local-storage-setup
    spec:
      hostNetwork: true
      containers:
      - name: local-storage-setup
        image: debian:bullseye-slim
        command: ["/bin/bash", "/scripts/setup-local-storage.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostfs
          mountPath: /mnt
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: hostfs
        hostPath:
          path: /mnt
      - name: scripts
        configMap:
          name: node-local-storage-setup
          defaultMode: 0744
      tolerations:
      - operator: Exists
      terminationGracePeriodSeconds: 0