apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-distributed
  resources:
    requests:
      storage: 10Gi
