apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
data:
  # These are example values - replace with your own base64 encoded values
  # echo -n "password" | base64
  postgres-password: UG9zdGdyZXNBZG1pblBhc3MwMQ==
  postgres-replication-password: UG9zdGdyZXNSZXBsaWNhdGlvblBhc3MwMQ==
  pgadmin-email: amFncmVlbkBnbXguZGU=
  pgadmin-password: UEdBZG1pblBhc3MwMQ==
